site_name: Blueprint Documentation
nav:
  - Home: index.md
  - 'Quick Start': quickStart.md
  - 'Tutorial': tutorial.md
  - 'Why Blueprint': whyBlueprint.md
  - Architecture: architecture.md
  - Examples: examples.md
  - Github Repo: https://github.com/steaks/blueprint
theme:
  name: gitbook
  highlightjs: true
plugins:
#  - search
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: sphinx
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition
